[package]
name = "pbase"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
indexmap = { version = "2.8", features = ["serde"] }
bytes = "1.10"
memmap = "0.7"
